[server]
server_url = "0.0.0.0:3300"
debug = true
token_secret = "xxx"

[database]
database_url = "mysql://root:root123@172.18.3.2:3306/storetest"

[logger]
log_dir = "logs/"
log_cup = 1000
log_temp_size = "5MB"
log_pack_compress = "lz4"
log_rolling_type = "All"
log_level = "debug"
